version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Banking@2023
      - MYSQL_DATABASE=banking_solution
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ../BankingSolution
    restart: on-failure
    ports:
      - 8081:8081
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: